### ISSUE TITLE
[Question] Does this work with github groups?

### ISSUE THREAD

**Issue by arka-g** [shufo/auto-assign-reviewer-by-files#135]
I would like to mention a github group for review instead of an individual user, does this library support that? In my testing, it does not seem to.

**Comment by avshyz-gs** [comment]
Hi, any update on this matter? :)

**Comment by shufo** [comment]
Sorry for late reply.

Just released https://github.com/shufo/auto-assign-reviewer-by-files/releases/tag/v1.1.4 with team reviewers support.
