### ISSUE TITLE
[node js] Upgrade to version 20

### ISSUE THREAD

**Issue by fmagaldea** [shufo/auto-assign-reviewer-by-files#249]
Same as you did in https://github.com/shufo/auto-assign-reviewer-by-files/issues/246 but now with node 20, should fix this recent Github warning:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: shufo/auto-assign-reviewer-by-files@v1.1.5. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

**Comment by shufo** [comment]
Released [v1.2.0](https://github.com/shufo/auto-assign-reviewer-by-files/releases/tag/v1.2.0) as node20 support
